# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{stonepath}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Bock"]
  s.date = %q{2009-08-25}
  s.description = %q{TODO}
  s.email = %q{dbock@codesherpas.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "History.txt",
     "Manifest.txt",
     "PostInstall.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/stonepath.rb",
     "lib/stonepath/acl.rb",
     "lib/stonepath/acl/controller.rb",
     "lib/stonepath/acl/role.rb",
     "lib/stonepath/acl/state.rb",
     "lib/stonepath/config.rb",
     "lib/stonepath/controller_hooks.rb",
     "lib/stonepath/extensions/activerecordbase.rb",
     "lib/stonepath/group.rb",
     "lib/stonepath/role.rb",
     "lib/stonepath/task.rb",
     "lib/stonepath/work_bench.rb",
     "lib/stonepath/work_item.rb",
     "lib/stonepath/work_owner.rb",
     "rails_generators/stonepath/stonepath_audit_table_generator.rb",
     "rails_generators/stonepath/stonepath_task_generator.rb",
     "script/console",
     "script/destroy",
     "script/generate",
     "test/app_root/app/controllers/application_controller.rb",
     "test/app_root/app/models/assignment.rb",
     "test/app_root/app/models/case.rb",
     "test/app_root/app/models/user.rb",
     "test/app_root/config/boot.rb",
     "test/app_root/config/database.yml",
     "test/app_root/config/environment.rb",
     "test/app_root/config/environments/in_memory.rb",
     "test/app_root/config/environments/mysql.rb",
     "test/app_root/config/environments/postgresql.rb",
     "test/app_root/config/environments/sqlite.rb",
     "test/app_root/config/environments/sqlite3.rb",
     "test/app_root/config/routes.rb",
     "test/app_root/db/migrate/01_create_users.rb",
     "test/app_root/db/migrate/02_create_assignments.rb",
     "test/app_root/db/migrate/03_create_cases.rb",
     "test/app_root/lib/console_with_fixtures.rb",
     "test/app_root/log/.gitignore",
     "test/app_root/script/console",
     "test/fixtures/users.yml",
     "test/test_group.rb",
     "test/test_helper.rb",
     "test/test_role.rb",
     "test/test_stonepath.rb",
     "test/test_workitem.rb",
     "test/test_workowner.rb"
  ]
  s.has_rdoc = true
  s.homepage = %q{http://github.com/bokmann/stonepath}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.1}
  s.summary = %q{Stonepath: stateful workflow modeling for rails}
  s.test_files = [
    "test/app_root/app/controllers/application_controller.rb",
     "test/app_root/app/models/assignment.rb",
     "test/app_root/app/models/case.rb",
     "test/app_root/app/models/user.rb",
     "test/app_root/config/boot.rb",
     "test/app_root/config/environment.rb",
     "test/app_root/config/environments/in_memory.rb",
     "test/app_root/config/environments/mysql.rb",
     "test/app_root/config/environments/postgresql.rb",
     "test/app_root/config/environments/sqlite.rb",
     "test/app_root/config/environments/sqlite3.rb",
     "test/app_root/config/routes.rb",
     "test/app_root/db/migrate/01_create_users.rb",
     "test/app_root/db/migrate/02_create_assignments.rb",
     "test/app_root/db/migrate/03_create_cases.rb",
     "test/app_root/lib/console_with_fixtures.rb",
     "test/test_group.rb",
     "test/test_helper.rb",
     "test/test_role.rb",
     "test/test_stonepath.rb",
     "test/test_workitem.rb",
     "test/test_workowner.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 2

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 2.0.0"])
    else
      s.add_dependency(%q<activerecord>, [">= 2.0.0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 2.0.0"])
  end
end
