# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
require 'rdoc/task'

require 'tasks/rails'


#require(File.join(File.dirname(__FILE__), 'vendor', 'gems', "**", 'lib', 'tasks', '*.rake'))

Dir["#{RAILS_ROOT}/vendor/gems/*/lib/tasks/*.rake"].sort.each { |rakefile| load rakefile }

